// Copyright (c) 2026 Claudius Tiberiu Iacob — Licensed under BSL 1.1. See LICENSE for details.
/**
 * @int3gra/cli - scaffoldGuide.js
 *
 * Builds the Markdown guide delivered to the developer's originally
 * requested path after `integra init` scaffolds the real working tree into
 * .integrations/<id>/live and turns it into a git repository.
 *
 * This is an action checklist for a developer who has never seen integra
 * before — not documentation. It says what to do and, where it isn't
 * obvious, why a step exists in one line. It does not explain how the
 * system is built, defend design choices, or duplicate anything the
 * README already covers — that content links out to the README instead.
 *
 * Kept separate from init.js so the guide's content can be unit-tested
 * without touching the filesystem.
 */

const README_URL = "https://github.com/ciacob/integra#readme";

const ON_YOUR_MACHINE = "**On your own machine:**";
const ON_THE_HOST      = "**Back on the host, over SSH:**";

/**
 * @param {object} params
 * @param {string} params.id          the integration id
 * @param {string} params.host        resolved public IP/hostname, or null if lookup failed
 * @param {string} params.liveDir     absolute path to .integrations/<id>/live on this host
 * @param {string} params.osUser      the OS user owning the live/ repo (for the clone command)
 * @returns {string} Markdown content
 */
export function buildScaffoldGuide({ id, host, liveDir, osUser }) {
  const cloneTarget = host ? `${osUser}@${host}:${liveDir}` : null;

  const cloneSection = [
    "## 1. Clone it",
    "",
    ON_YOUR_MACHINE,
    "",
    "Not over the SSH session you used to set this up — clone this onto the actual machine you'll write code on. There's no editor or IDE on the host.",
    "",
    "```bash",
    "git clone <user>@<host>:<path> <local-folder-name>",
    "```",
    "",
    cloneTarget
      ? [
          "e.g.:",
          "",
          "```bash",
          `git clone ${cloneTarget} ${id}`,
          "```",
          "",
          "> note: this host/address was auto-detected and may be wrong (different network, VPN, jump host) — if it doesn't work, ask whoever administers this host for the right one.",
        ].join("\n")
      : [
          "We couldn't auto-detect this host's address — ask whoever administers it for the right user/host, then fill in the general form above.",
        ].join("\n"),
    "",
    "> note: if you can SSH in, you should be able to clone and push — but that's not guaranteed by SSH access alone; ask if either fails.",
  ].join("\n");

  return [
    `# ${id}`,
    "",
    `This integration has been scaffolded. You must never edit it at \`${liveDir}\` directly — clone it and work from your clone.`,
    "",
    cloneSection,
    "",
    "## 2. Set up your dev environment",
    "",
    "```bash",
    "cd " + id,
    "cp .env.example .env.dev      # fill in non-production credentials",
    "git checkout -b <your-branch-name>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `cp .env.example .env.dev`,
    `git checkout -b my-patch`,
    "```",
    "",
    "> note: for help writing connections/maps/processes/resolvers, see the README: " + README_URL,
    "",
    "## 3. Build, push, and verify",
    "",
    "```bash",
    "# ...edit connections/, maps/, processes/, resolvers/...",
    "git add -A && git commit -m \"<message>\"",
    "git push origin <your-branch-name>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    "git add -A && git commit -m \"add incident sync\"",
    "git push origin my-patch",
    "```",
    "",
    "> note: nothing local is \"seen\" until pushed — validate/test/run always read what you just pushed, never your working copy.",
    "",
    ON_THE_HOST,
    "",
    "Validate the structure:",
    "",
    "```bash",
    "integra validate --id <id> --branch <your-branch-name>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra validate --id ${id} --branch my-patch`,
    "```",
    "",
    "Add fixtures under `test/fixtures/` and mock-test:",
    "",
    "```bash",
    "integra test --id <id> --branch <your-branch-name>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra test --id ${id} --branch my-patch`,
    "```",
    "",
    "> note: see the README for fixture format and layout: " + README_URL,
    "",
    "Run it for real, against your dev credentials and your entry process:",
    "",
    "```bash",
    "integra run <process-id> --id <id> --branch <your-branch-name> --env .env.dev",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra run sync-incident --id ${id} --branch my-patch --env .env.dev`,
    "```",
    "",
    "> note: if this integration is a listener, this starts a real server that keeps running until you stop it yourself.",
    "",
    "## 4. Promote to production",
    "",
    ON_YOUR_MACHINE,
    "",
    "```bash",
    "cp .env.example .env          # fill in PRODUCTION credentials, commit it like any other file",
    "git add -A && git commit -m \"add production credentials\" && git push origin <your-branch-name>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    "git add -A && git commit -m \"add production credentials\" && git push origin my-patch",
    "```",
    "",
    ON_THE_HOST,
    "",
    "On demand, confirm it against production before going further:",
    "",
    "```bash",
    "integra run <process-id> --id <id> --branch <your-branch-name> --env .env",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra run sync-incident --id ${id} --branch my-patch --env .env`,
    "```",
    "",
    "Check out, review/edit, then publish or release this integration's own configuration (schedule, enabled state, etc.) — see the README for the registry format: " + README_URL,
    "",
    "```bash",
    "integra-manager checkout <id>",
    "# ...review/edit the staged file if needed...",
    "integra-manager publish <id>",
    "# or, if you change nothing: integra-manager uncheckout <id>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra-manager checkout ${id}`,
    `integra-manager publish ${id}`,
    "```",
    "",
    "Deploy — this restarts the integration as a resident process on production credentials:",
    "",
    "```bash",
    "integra-manager deploy <id> --branch <your-branch-name>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra-manager deploy ${id} --branch my-patch`,
    "```",
    "",
    "> note: deploy refuses if your branch doesn't fast-forward cleanly — rebase in your clone and push again.",
    "",
    "Then watch the logs and the actual target systems for a while:",
    "",
    "```bash",
    "integra-manager logs <id>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra-manager logs ${id}`,
    "```",
    "",
    "## 5. Patch it later",
    "",
    ON_YOUR_MACHINE,
    "",
    "Decide where the patch starts from — what's deployed now, or an earlier branch/commit (depends on what you're fixing and this integration's own history):",
    "",
    "```bash",
    "git checkout -b <patch-branch-name> <starting-point>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    "git checkout -b fix-incident-priority my-patch",
    "```",
    "",
    "Then repeat step 3 (build, push, verify) on this branch.",
    "",
    "> note: to test the patch against production before deploying, temporarily `integra-manager disable <id>`, run with `--env .env`, then re-`enable` it — or just deploy when confident.",
    "",
    "When confident, deploy it the same way as step 4.",
    "",
    "## 6. Undo a bad deploy",
    "",
    ON_THE_HOST,
    "",
    "Check recent deploys:",
    "",
    "```bash",
    "integra-manager deploy-history <id>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra-manager deploy-history ${id}`,
    "```",
    "",
    "Roll back to the previous one:",
    "",
    "```bash",
    "integra-manager undeploy <id>",
    "```",
    "",
    "e.g.:",
    "",
    "```bash",
    `integra-manager undeploy ${id}`,
    "```",
    "",
    "> note: if that's not enough (the bug predates the previous deploy too), go through step 5 again, starting from an earlier known-good branch or commit.",
    "",
    "## More help",
    "",
    "Everything else — architecture, the registry, authentication, fixtures in",
    "depth, listener integrations, and more — is in the README:",
    "",
    README_URL,
    "",
  ].join("\n");
}
